version: '3.8'

services:
    web:
      build: .
      command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
      environment:
        - ENVIRONMENT=development
        - SECRET_KEY=django-insecure-w(e(d@z0t^w+4m-&8wvy42^oatvnv$$%*^ph9wk=*n_yx*t#zjq
        - DEBUG=1
        - STRIPE_TEST_PUBLISHABLE_KEY=<publish_key>
        - STRIPE_TEST_SECRET_KEY=<secret_key>
      volumes:
        - .:/code
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
      image: postgres:11
      environment:
        POSTGRES_PASSWORD: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: